"""adicionando coluna de quantidade a tabela menu

Revision ID: 3ac6e27940ca
Revises: c36e91fb019e
Create Date: 2023-11-03 16:13:13.061654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac6e27940ca'
down_revision: Union[str, None] = 'c36e91fb019e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('qntd', sa.Integer(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'qntd')
    # ### end Alembic commands ###
