"""coluna fabrication palce alterado para str

Revision ID: c36e91fb019e
Revises: 4b90ac7e5cec
Create Date: 2023-11-02 21:39:54.185313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36e91fb019e'
down_revision: Union[str, None] = '4b90ac7e5cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'fabrication_place')
    op.add_column('menu', sa.Column('fabrication_place', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'fabrication_place')
    op.add_column('menu', sa.Column('fabrication_place', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
